<a href="https://colab.research.google.com/github/khushboo149/ML-project--heart-disease/blob/main/Lab7-SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries and load data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Get the Data

We'll use the built in breast cancer dataset from Scikit Learn. Note the load function:

In [6]:
import pandas as pd

df = pd.read_csv('/USA_Housing.csv')
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

**The data set is presented in a dictionary form**

In [8]:
df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

**We can grab information and arrays out of this dictionary to create data frame and understand the features**

**The description of features are as follows**

In [9]:
X = df[['Avg. Area Income',
        'Avg. Area House Age',
        'Avg. Area Number of Rooms',
        'Avg. Area Number of Bedrooms',
        'Area Population']]

y = df['Price']

**Show the feature names**

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=101
)

## Set up the DataFrame

In [ ]:
df = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=101
)

**Is there any missing data?**

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**What are the 'target' data in the data set?**

In [13]:
from sklearn.svm import SVR

model = SVR(kernel='rbf')

model.fit(X_train, y_train)

SVR()

**Adding the target data to the DataFrame**

In [14]:
predictions = model.predict(X_test)

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

print("MAE:", mean_absolute_error(y_test, predictions))
print("MSE:", mean_squared_error(y_test, predictions))
print("RMSE:", np.sqrt(mean_squared_error(y_test, predictions)))

MAE: 281681.48325999465
MSE: 124770766115.52805
RMSE: 353229.0561597786

In [16]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C':[1,10,100],
    'gamma':[0.1,0.01,0.001],
    'kernel':['rbf']
}

grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=2)

grid.fit(X_train, y_train)

print(grid.best_params_)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   1.1s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.9s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.7s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   1.2s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.7s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   1.7s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   1.7s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   1.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   1.1s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.9s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   1.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.8s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.9s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.9s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.9s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   1.1s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   1.1s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.8s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.8s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.5s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.5s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.5s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.5s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.8s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.8s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.8s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.9s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.8s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.7s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.8s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.6s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.8s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.7s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.1s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.3s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   1.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.7s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.6s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.6s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.5s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.5s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.5s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.5s
{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}